apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: etl-data-pvc
  namespace: default
spec:
  accessModes:
  - ReadWriteOnce  # Changed from ReadWriteMany
  resources:
    requests:
      storage: 1Gi