# Docker/Dockerfile-load
FROM python:3.11-slim

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \
    gcc \
    python3-dev \
    && rm -rf /var/lib/apt/lists/*
RUN pip install --no-cache-dir pymongo

COPY src/config.py src/config.py
COPY src/load.py src/load.py
COPY scripts/load_chunk.py scripts/load_chunk.py

ENV PYTHONUNBUFFERED=1
ENV MONGODB_URI=mongodb://mongodb:27017/
ENV INPUT_PATH=/data/transformed_chunk_0.json

CMD ["python", "scripts/load_chunk.py"]